project_name: kubectl-loadsim
release:
  github:
    owner: loganrobertclemons
    name: kubectl-loadsim
builds:
  - id: kubectl-loadsim
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/plugin/main.go
    ldflags: -s -w
      -X github.com/loganrobertclemons/kubectl-loadsim/pkg/version.version=
archives:
  - id: kubectl-loadsim
    builds:
    - kubectl-loadsim
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
