apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: kubectl-loadsim
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/loganrobertclemons/kubectl-loadsim/releases/download/v0.1.0/kubectl-loadsim_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./kubectl-loadsim"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-loadsim"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/loganrobertclemons/kubectl-loadsim/releases/download/v0.1.0/kubectl-loadsim_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./kubectl-loadsim"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-loadsim"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/loganrobertclemons/kubectl-loadsim/releases/download/v0.1.0/kubectl-loadsim_windows_amd64.zip
    sha256: ""
    files:
    - from: "/kubectl-loadsim.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-loadsim.exe"
  shortDescription: A new plugin
  homepage: https://github.com/loganrobertclemons/kubectl-loadsim
  caveats: |
    Usage:
      $ kubectl kubectl-loadsim

    For additional options:
      $ kubectl kubectl-loadsim --help
      or https://github.com/loganrobertclemons/kubectl-loadsim/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
